ZhigaoXIE_coursework_week6
GiggleLiu/ModernScientificComputing pull request #27
Opened 2023-03-27 02:26 UTC by nekokani

2023-04-02 10:26 UTC, ArrogantGao requested changes
As you can see your new branches still contain all the old files, you should not submit them again and again, please remove them from your new submission.
If you have difficulities on that, contact us on zulip and we will help you.
You also need to revise your prrevious work, that is also a vital part of the assignments.

2023-04-02 10:26 UTC, ArrogantGao commented on courseworks/week6/ZhigaoXIE/Q2.jl
> +    y = spzeros(T, size(A, 1))
As we mentioned in the class, it not a wise idea to used $n \times 1$ sparse matrix to represent a 1d array because it is actually full.

2023-04-21 08:48 UTC, nekokani commented
Sorry for making confusion. Now, i have rearrange my courseworks files and make them in correct submitting order.

2023-04-22 13:09 UTC, ArrogantGao requested changes

2023-04-22 13:09 UTC, ArrogantGao commented on courseworks/week6/ZhigaoXIE/HW_FFTW.jl
> +    resulting_vector = real(ifft(fft_product))[1:n_signal + n_fw - 1]
What we need is the
```
resulting_vector = abs(ifft(fft_product))[1:n_signal + n_fw - 1]
```

2023-05-17 08:38 UTC, nekokani commented
Hello, coursework week6 has been revised. Thx.

2023-05-17 11:55 UTC, merged