Exercise lesson meterials, Xuanzhao Gao
GiggleLiu/ModernScientificComputing pull request #30
Opened 2023-03-29 05:04 UTC by ArrogantGao

This branch contains the materials of the exercise lesson on last week.

2023-03-30 19:57 UTC, GiggleLiu requested changes

2023-03-30 19:57 UTC, GiggleLiu commented on courseworks/exercise_lesson/lesson1/lesson1.pptx
Good. Do you mind compressing this file a bit? e.g. by coverting it to PDF. 9MB is too big.

2023-03-30 19:57 UTC, GiggleLiu commented on courseworks/week6/xuanzhaogao/hw6.ipynb
The plot is not shown in the notebook.

2023-03-30 19:57 UTC, GiggleLiu commented on courseworks/exercise_lesson/lesson1/lesson1.ipynb
Good job.

2023-03-30 20:10 UTC, GiggleLiu commented on courseworks/week6/xuanzhaogao/hw6.ipynb
It seems you commited some old files to this PR. ;D

2023-04-02 07:44 UTC, ArrogantGao commented on courseworks/exercise_lesson/lesson1/lesson1.pptx
I found my slides only contains the questions, so that I directly removed it.

2023-04-02 07:50 UTC, ArrogantGao commented on courseworks/week6/xuanzhaogao/hw6.ipynb
Sorry about that, I removed these files.
The fiugure may be a little bit to large so that github can not render it properly. In my 'week6' branch I saved the figure and showed it via markdown sentences.

2023-04-02 09:29 UTC, merged