week1
GiggleLiu/ModernScientificComputing pull request #4
Opened 2023-02-15 09:46 UTC by ArrogantGao

2023-02-15 09:48 UTC, ArrogantGao commented
Xuanzhao Gao

2023-03-04 20:22 UTC, GiggleLiu requested changes
Good job.

2023-03-04 20:22 UTC, GiggleLiu commented on courseworks/week2/Xuanzhao_Gao/HW2.md
> +
## About 3x+1.ipynb
1. Instead printing the result, the notebook is supposed to include a test.
2. The test should cover all Int32 integers.

2023-03-04 20:22 UTC, GiggleLiu commented on courseworks/week1/XuanzhaoGao/HW1.md
> +   and these two times are almost the same.
👍🏾

2023-03-04 20:22 UTC, GiggleLiu commented on courseworks/week1/XuanzhaoGao/lscpu.res
> +Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopol
You CPU has avx512 support. Its double precision floating point computing power is at least:
```
6 x 2.6 x 8 (avx512) x 2 (fma)
```
Measuring the CPU performance by benchmarking GEMM is more straight forward.

2023-03-04 20:22 UTC, GiggleLiu commented on courseworks/week1/XuanzhaoGao/HW1.md
> +   1. **Associativity of addition**: Yes
This answer should be fixed.

2023-03-16 03:23 UTC, ArrogantGao commented
I remove the submission of week1 and week2 from my main branch and build a new branch

2023-03-16 03:23 UTC, closed without merging